name: All-Project-CD

on:
  push:
    branches: [ "master" ]

jobs:
  checkout-repo:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

  create-env:
    runs-on: self-hosted
    needs: [ checkout-repo ]

    env:
      DEBUG: 'True'
      ALLOWED_HOSTS: '*'

      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      DB_USER: ${{ secrets.DB_USER }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Write Django Env
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DEBUG=${{ env.DEBUG }}" >> .env
          echo "ALLOWED_HOSTS=${{ env.ALLOWED_HOSTS }}" >> .env
      - name: Write DB Env
        run: |
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

  build:
    runs-on: self-hosted
    needs: [ create-env, checkout-repo ]

    steps:
      - name: Run Tests
        run: |
          whoami
          groups
          echo
          ls -la
          echo
      - name: Run Docker Tests
        run: |
          docker ps -a
          docker images



#docker-compose down
#docker rmi test_nginx_gunicorn_django_ci_cd_nginx test_nginx_gunicorn_django_ci_cd_backend
#docker-compose up --build -d
